### ISSUE TITLE
Puppet may inadvertently remove NAT rules for docker

### ISSUE THREAD

**Issue by andylytical** [ncsa/control-repo#11]
Update

data/role/puppet_master.yaml#L10

to use better regex's for ignoring NAT iptables rules from purge.

```
POSTROUTING:nat:IPv4: [ "-s 172\.", "-d 172\."]
```

**Comment by andylytical** [comment]
Use multiline array syntax for improved readability.

```
POSTROUTING:nat:IPv4:
  - "-s 172\."
  - "-d 172\."
```

**Comment by bsper2** [comment]
This has been completed in : https://github.com/ncsa/control-repo/pull/12
